#!/usr/bin/env bash
# =============================================================================
# start-laya.sh — Start the Laya (System 1 decision model) server
# =============================================================================
#
# Generated by tasks/setup-laya.sh — do not edit manually. Re-running the
# setup script overwrites this file.
#
# Starts laya-serve from the local venv in the FOREGROUND (Ctrl-C stops it).
# Laya answers typed choice/score/noul questions on POST /v1/systemone —
# see docs/research/laya-system1-model-research.md.
#
# Configuration via environment variables. Any variable already set in your
# environment takes precedence over the defaults below:
#   LAYA_HOST      bind address                     (default: 127.0.0.1)
#   LAYA_PORT      bind port                        (default: 8000)
#   LAYA_DEVICE    torch device for all checkpoints (default: ${LAYA_DEVICE}, auto-detected at setup)
#   LAYA_PRELOAD   build checkpoints at startup     (default: 1)
#   LAYA_MODELS    comma list of checkpoints to preload (default: all)
#   LAYA_AUTO_TASK auto-route to typed-decisions checkpoint (default: 0)
#   LAYA_API_KEY   if set, require "Authorization: Bearer <key>" (default: none)
#   LAYA_LOG_LEVEL uvicorn log level                (default: info)
#
# USAGE:
#   ./start-laya.sh                  # start on 127.0.0.1:8000 (foreground)
#   LAYA_PORT=8010 ./start-laya.sh   # start on a different port
#   ./start-laya.sh --help           # show help and exit
#
# REFERENCE:
#   Test once running: curl http://127.0.0.1:8000/docs
# =============================================================================

set -euo pipefail

LAYA_SERVE="${VENV_LAYA_SERVE}"
LAYA_DEVICE_DEFAULT="${LAYA_DEVICE}"

usage() {
  cat <<EOF
Usage: $0 [OPTIONS]

Starts the Laya server (laya-serve) from ${LAYA_SERVE} in the foreground.

Options:
  -h, --help     Show this help and exit

Environment variables (override the built-in defaults):
  LAYA_HOST      Bind address (default: 127.0.0.1)
  LAYA_PORT      Bind port (default: 8000)
  LAYA_DEVICE    torch device, cpu|cuda (default: ${LAYA_DEVICE_DEFAULT})
  LAYA_PRELOAD   Build checkpoints at startup (default: 1)
  LAYA_MODELS    Comma list of checkpoints to preload (default: all)
  LAYA_AUTO_TASK Auto-route to typed-decisions checkpoint (default: 0)
  LAYA_API_KEY   If set, require "Authorization: Bearer <key>" (default: none)
  LAYA_LOG_LEVEL Uvicorn log level (default: info)

Test once running: curl http://127.0.0.1:\${LAYA_PORT}/docs
EOF
}

case "${1:-}" in
  -h|--help) usage; exit 0 ;;
  "") ;;
  *) echo "Unknown option: $1 (use --help for usage)" >&2; exit 1 ;;
esac

: "${LAYA_HOST:=127.0.0.1}"
: "${LAYA_PORT:=8000}"
: "${LAYA_DEVICE:=$LAYA_DEVICE_DEFAULT}"
: "${LAYA_PRELOAD:=1}"
export LAYA_HOST LAYA_PORT LAYA_DEVICE LAYA_PRELOAD

echo "Starting laya-serve on ${LAYA_HOST}:${LAYA_PORT} (device: ${LAYA_DEVICE})"
echo "Answers on POST http://${LAYA_HOST}:${LAYA_PORT}/v1/systemone — Ctrl-C stops the server."
exec "${LAYA_SERVE}"
